<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Notestra annotations — see mdfile/NOTESTRA_FUNCTIONAL_SPEC.md, Section 9.
     * `client_uuid` is generated by the frontend at draw-time and is the
     * idempotency key the batched sync endpoint upserts on, so an
     * optimistically-rendered stroke keeps the same identity before and
     * after the backend has seen it. `deleted_at` is a soft delete (not
     * Laravel's SoftDeletes trait) so an autosave batch can "delete" an
     * annotation the same way it upserts one, in a single transaction.
     */
    public function up(): void
    {
        Schema::create('material_annotations', function (Blueprint $table) {
            $table->id();
            $table->uuid('client_uuid')->unique()->nullable();
            $table->foreignId('material_id')->constrained()->cascadeOnDelete();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->unsignedSmallInteger('page_number');
            $table->string('type'); // drawing|highlight|text
            $table->json('data'); // normalized (0-1) coordinates, see spec Section 6
            $table->timestamp('deleted_at')->nullable();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('material_annotations');
    }
};
